package dev.comfyfluffy.caustica.rt.pipeline;

public enum DlssgTransitionReason {
    NONE, USER_DISABLED, MENU, INPUTS_INVALID, NO_FREE_INPUT_SLOT, COMPLETION_LATE,
    COMPLETION_UNKNOWN, FRAME_DISCONTINUITY, EXPECTED_CPU_STALL, EXPECTED_GPU_STALL,
    CAMERA_CUT, TELEPORT, DIMENSION_CHANGE, RESOURCE_RELOAD, SWAPCHAIN_CHANGE,
    PRESENT_OUT_OF_DATE, QUEUE_POLICY_CHANGE, RUNTIME_STATUS, API_ERROR, DEVICE_LOST,
    ABI_MISMATCH, UNSUPPORTED
}
