package dev.comfyfluffy.caustica.rt.pipeline;

public enum DlssgRuntimeState {
    UNINITIALIZED, UNAVAILABLE, IDLE, WARMUP, ACTIVE, SUSPENDED_MENU,
    SUSPENDED_HITCH, SUSPENDED_INPUT_STARVATION, SUSPENDED_OUT_OF_BAND,
    RECONFIGURING, RECOVERING, FATAL
}
