package dev.comfyfluffy.caustica.rt.pipeline;

public enum FrameLifecycleState {
    EMPTY, TOKEN_ACQUIRED, SLEEP_COMPLETE, SIMULATION_ACTIVE, SIMULATION_COMPLETE,
    RENDER_SUBMIT_ACTIVE, RENDER_SUBMIT_COMPLETE, PRESENT_ACTIVE, COMPLETE, ABANDONED
}
